name: Lint Checkings
on: [push, pull_request]
permissions: read-all
jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Executables & compile_commands.json
        run: make -j$(nproc) all

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
